name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  test-script: npm run test:cov
